name: issue
description: A CLI tool to help cli package authors make raising issues like bug reports more interactive for their users.
version: 0.0.4
repository: https://www.github.com/werainkhatri/issue
issue_tracker: https://github.com/werainkhatri/issue/issues

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  ansi_styles: ^0.3.2+1
  equatable: ^2.0.5
  interact: ^2.1.1
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
